apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: self-healing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: self-healing-microservices-user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
